In [1]:
import numpy as np
from sklearn import preprocessing
## to import scaling, we need to import the above module.

In [13]:
X = np.array([[1., -1., 2.],
              [2.,  0., 0.],
              [0., 1., -1.]])
X

array([[ 1., -1.,  2.],
       [ 2.,  0.,  0.],
       [ 0.,  1., -1.]])

In [4]:
## this scale() centres the data around the mean or it scales x for us.
## It makes means to be 0 and it makes variance to be 1.
 
x_scaled = preprocessing.scale(X)

In [6]:
## we can also find mean value

x_scaled.mean(axis = 0)

array([0., 0., 0.])

In [9]:
## checking standard deviation value
x_scaled.std(axis = 0)

array([1., 1., 1.])

In [11]:
## One problem is that lets say we have xtrain and xtest data.
## Now if we apply scaling on both of them seprately, it will create a problem on regression.
## Now solve this problem, we combine the data and then apply scaling on it.
## But when we deploy the model, the model trains witht the training data.The testing data comes afterwards.
## So to solve this problem, we first train the modelwith training data AND STORE ITS PARAMETER.
## And then when the testing data comes, we scale the testing data with the same parameter we store.
## For that we use preprocessing.StandardScaler() it cannot be done with scalar(), it returns an object.
## Then you can fit your scaler with training data. i.e. finds the parameter that fits the training data.
## once weve done the fitting, we can transform any data we want.



scaler = preprocessing.StandardScaler()
scaler.fit(X)

scaler.transform(X)

## As we can see, it has transformed the data in the same way scalar() has done.

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [12]:
## we can transform any data.(make sure it is 2d array.)

x_test = [[1,1,0]]
scaler.transform(x_test)

array([[ 0.        ,  1.22474487, -0.26726124]])

In [ ]:
## there are many types of standardscalers.