In [1]:
import numpy as np
import pandas as pd

In [2]:
df_training=np.genfromtxt('0000000000002417_training_boston_x_y_train.csv',delimiter=',')
df_test=np.genfromtxt('0000000000002417_test_boston_x_test.csv',delimiter=',')
#df_training.head()
x_train=df_training[:,:-1]
y_train=df_training[:,-1]
x_train

array([[-0.40784991, -0.48772236, -1.2660231 , ..., -0.30309415,
         0.41057102, -1.09799011],
       [-0.40737368, -0.48772236,  0.24705682, ...,  0.1130321 ,
         0.29116915, -0.52047412],
       [ 0.1251786 , -0.48772236,  1.01599907, ...,  0.80657583,
        -3.79579542,  0.89107588],
       ...,
       [-0.40831101, -0.48772236,  0.24705682, ...,  0.1130321 ,
         0.33206621, -0.33404299],
       [-0.41061997, -0.48772236, -1.15221381, ..., -0.71922039,
         0.203235  , -0.74475218],
       [ 0.34290895, -0.48772236,  1.01599907, ...,  0.80657583,
         0.38787479, -1.35871335]])

In [3]:
from sklearn.preprocessing import StandardScaler
SS=StandardScaler()
x_train[:,:]=SS.fit_transform(x_train[:,:])
x_train

array([[-0.40098068, -0.49042688, -1.28149216, ..., -0.32264241,
         0.42027996, -1.10095452],
       [-0.40053396, -0.49042688,  0.20753471, ...,  0.09391068,
         0.30257958, -0.53143278],
       [ 0.09900799, -0.49042688,  0.96425328, ...,  0.78816582,
        -3.72614514,  0.86057789],
       ...,
       [-0.40141319, -0.49042688,  0.20753471, ...,  0.09391068,
         0.34289385, -0.34758231],
       [-0.40357903, -0.49042688, -1.16949207, ..., -0.7391955 ,
         0.21589851, -0.75260628],
       [ 0.30324229, -0.49042688,  0.96425328, ...,  0.78816582,
         0.39790715, -1.35806871]])

In [3]:
df_test=np.genfromtxt('0000000000002417_test_boston_x_test.csv',delimiter=',')
df_test

array([[ 2.91816626, -0.48772236,  1.01599907, ...,  0.80657583,
        -1.59755122,  1.04106182],
       [-0.40339151, -0.48772236,  0.40609801, ..., -1.13534664,
         0.44105193, -0.89473812],
       [-0.4131781 , -0.48772236,  0.11573841, ...,  1.17646583,
         0.44105193, -0.50084979],
       ...,
       [-0.41001449,  2.08745172, -1.37837329, ..., -0.0719129 ,
         0.39094481, -0.68167397],
       [-0.40317611, -0.48772236, -0.37597609, ...,  1.13022958,
         0.34007019,  0.20142086],
       [-0.13356344, -0.48772236,  1.2319449 , ..., -1.73641788,
        -2.93893082,  0.48877712]])

In [5]:
df_test[:,:]=SS.fit_transform(df_test[:,:])
df_test

array([[ 3.88203164, -0.47968561,  1.19321481, ...,  0.86318341,
        -1.72394297,  1.14793924],
       [-0.4496825 , -0.47968561,  0.54572124, ..., -1.07706957,
         0.41293844, -0.87954882],
       [-0.4624454 , -0.47968561,  0.23746473, ...,  1.23275541,
         0.41293844, -0.46700418],
       ...,
       [-0.45831967,  2.09168571, -1.34873963, ..., -0.01455008,
         0.36041572, -0.656393  ],
       [-0.4494016 , -0.47968561, -0.28455761, ...,  1.18655891,
         0.30708851,  0.26852914],
       [-0.09779398, -0.47968561,  1.42247091, ..., -1.67762407,
        -3.12998863,  0.56949587]])

In [4]:
# changes are we pass m as array with last element as c in it.
# We will not have m_slope or c_slope as well, we will have another array whoch will start with all 0's and we will update 
# these values within this array.  

def step_gradient(X, Y, learning_rate, m):
    
    # m_slope = 0
    # c_slope = 0
    
    features = X.shape[1]
    mslope  = np.array([0.0 for i in range(features)])   # make sure we take numpy array here or else it will give typeerror.
    M = len(X)
    for i in range(M): # going through all data
        x = X[i, :]
        y = Y[i]
        
        # calculating m*x for a row here
        # this will return an array of mx.
        mx = m*x
        for j in range(features):
            mslope[j] +=   (-2/M)* (y - mx.sum(axis = 0) ) * x[j]  
    new_m = m - learning_rate*mslope
    m = new_m
    return m 

In [5]:
def gd(X, Y, learning_rate, num_iterations):
    m = [0 for i in range(X.shape[1])]
    for i in range(num_iterations):
        m= step_gradient(X,Y, learning_rate, m)
        print(i, 'Cost: ', cost(X, Y, m))
    return m


In [6]:
def cost(X, Y, m):
    total_cost = 0
    M = len(X)
    
    for i in range(M):
        x = X[i, :]
        y = Y[i]
        total_cost += (1/M) * ( y - (m*x).sum() )**2
    return total_cost

In [7]:
# appending one at the last row
df_test = np.c_[df_test, np.ones(df_test.shape[0])]
x_train = np.c_[x_train, np.ones(x_train.shape[0])]


In [8]:
def run():
    #data = np.loadtxt("https://files.codingninjas.in/data-6984.csv", delimiter=",")

    learning_rate = 0.1
    num_iterations = 1000
    
    # here we adding columns with all 1's for Generic Case.
    #X = data[:, :-1]
    #Y = data[:, -1]
    #for i in x_train:
    #    i = np.append(i, 1.0)
    m = gd(x_train, y_train, learning_rate, num_iterations)
    print(m, m[-1])# As last element of m is c.
    return m
    
    

In [9]:
m = run()
m

0 Cost:  374.24035597919686
1 Cost:  245.37909656079904
2 Cost:  165.10614192173668
3 Cost:  114.49508621191686
4 Cost:  82.43432664281796
5 Cost:  62.041704688310936
6 Cost:  49.0154746660482
7 Cost:  40.65519326019772
8 Cost:  35.25972835067592
9 Cost:  31.754121492629718
10 Cost:  29.457161634001743
11 Cost:  27.936007022144533
12 Cost:  26.914922412896374
13 Cost:  26.217802951980175
14 Cost:  25.731872822963105
15 Cost:  25.38469911771804
16 Cost:  25.129603525591076
17 Cost:  24.936384410518777
18 Cost:  24.785404792037365
19 Cost:  24.66381822190748
20 Cost:  24.56315514362143
21 Cost:  24.477776518190055
22 Cost:  24.403881200700226
23 Cost:  24.338867434896198
24 Cost:  24.280921148348455
25 Cost:  24.228749732407817
26 Cost:  24.18140930058519
27 Cost:  24.138192120101166
28 Cost:  24.09855285948923
29 Cost:  24.06205993819115
30 Cost:  24.028363158977218
31 Cost:  23.997171942483217
32 Cost:  23.968240497783352
33 Cost:  23.941357557710433
34 Cost:  23.916339140893513
35 Cos

286 Cost:  23.466305639381545
287 Cost:  23.466298894853725
288 Cost:  23.466292328793624
289 Cost:  23.466285936478407
290 Cost:  23.466279713310247
291 Cost:  23.466273654813058
292 Cost:  23.466267756629183
293 Cost:  23.466262014516285
294 Cost:  23.466256424344373
295 Cost:  23.466250982092692
296 Cost:  23.466245683846946
297 Cost:  23.466240525796433
298 Cost:  23.466235504231324
299 Cost:  23.46623061553986
300 Cost:  23.466225856206062
301 Cost:  23.466221222806798
302 Cost:  23.46621671200972
303 Cost:  23.46621232057047
304 Cost:  23.466208045330742
305 Cost:  23.46620388321568
306 Cost:  23.466199831231886
307 Cost:  23.466195886465112
308 Cost:  23.46619204607825
309 Cost:  23.466188307309313
310 Cost:  23.46618466746935
311 Cost:  23.466181123940583
312 Cost:  23.46617767417455
313 Cost:  23.466174315690186
314 Cost:  23.46617104607211
315 Cost:  23.46616786296878
316 Cost:  23.466164764091005
317 Cost:  23.4661617472101
318 Cost:  23.46615881015634
319 Cost:  23.46615595

570 Cost:  23.466050872790774
571 Cost:  23.46605086946845
572 Cost:  23.466050866234053
573 Cost:  23.466050863085226
574 Cost:  23.466050860019724
575 Cost:  23.466050857035338
576 Cost:  23.466050854129904
577 Cost:  23.46605085130137
578 Cost:  23.466050848547667
579 Cost:  23.46605084586683
580 Cost:  23.466050843256916
581 Cost:  23.466050840716072
582 Cost:  23.466050838242435
583 Cost:  23.466050835834274
584 Cost:  23.466050833489845
585 Cost:  23.466050831207422
586 Cost:  23.466050828985395
587 Cost:  23.46605082682217
588 Cost:  23.466050824716206
589 Cost:  23.466050822665924
590 Cost:  23.46605082066991
591 Cost:  23.46605081872671
592 Cost:  23.466050816834947
593 Cost:  23.46605081499318
594 Cost:  23.46605081320022
595 Cost:  23.46605081145464
596 Cost:  23.466050809755284
597 Cost:  23.466050808100878
598 Cost:  23.46605080649026
599 Cost:  23.466050804922247
600 Cost:  23.466050803395714
601 Cost:  23.4660508019096
602 Cost:  23.466050800462796
603 Cost:  23.46605079

850 Cost:  23.46605074729911
851 Cost:  23.46605074729729
852 Cost:  23.46605074729549
853 Cost:  23.466050747293785
854 Cost:  23.46605074729211
855 Cost:  23.46605074729047
856 Cost:  23.466050747288854
857 Cost:  23.466050747287305
858 Cost:  23.466050747285827
859 Cost:  23.466050747284356
860 Cost:  23.466050747282928
861 Cost:  23.466050747281496
862 Cost:  23.466050747280157
863 Cost:  23.466050747278846
864 Cost:  23.466050747277542
865 Cost:  23.46605074727629
866 Cost:  23.466050747275066
867 Cost:  23.466050747273904
868 Cost:  23.466050747272746
869 Cost:  23.46605074727162
870 Cost:  23.46605074727051
871 Cost:  23.466050747269446
872 Cost:  23.466050747268415
873 Cost:  23.466050747267428
874 Cost:  23.46605074726644
875 Cost:  23.46605074726547
876 Cost:  23.466050747264532
877 Cost:  23.46605074726363
878 Cost:  23.466050747262734
879 Cost:  23.466050747261896
880 Cost:  23.466050747261043
881 Cost:  23.466050747260237
882 Cost:  23.466050747259448
883 Cost:  23.4660507

array([-9.38080610e-01,  7.41033999e-01,  1.16903020e-02,  7.80873861e-01,
       -2.17455732e+00,  2.35429667e+00,  1.23337955e-01, -2.95232364e+00,
        2.53296549e+00, -1.70290056e+00, -2.25151951e+00,  5.88354232e-01,
       -4.26368148e+00,  2.26772333e+01])

In [24]:
y_pred=np.array((m*df_test).sum(axis=1))
y_pred

array([11.11698857, 28.73123179, 22.52767967, 23.98773544, 20.5127218 ,
        1.903572  , 30.5632182 , 24.80873648, 18.47344369, 23.50901754,
       23.92611909, 17.39196661, 16.53832262, 21.19302292, 43.40713624,
       23.27117339, 24.21579025, 27.59059768, 19.4918822 , 31.27879122,
       23.70265502, 24.86768544, 34.25039504, 37.36744949, 31.43195747,
       16.26932573, 23.40660975, 32.8380039 , 25.75340271, 34.63639151,
       16.49655849, 25.9158779 , 23.38031014, 25.22843375, 13.90930706,
       29.74010973, 26.03032084, 20.26513089, 23.90142271,  8.15908721,
        7.39932043, 28.72256922, 28.95609644, 19.71212956, 20.07201428,
        1.84845874, 39.87852706, 25.66760954, 29.76434892, 16.32638294,
       17.42670809, 41.03223994, 17.13451401, 20.91513729, 15.12528138,
       21.25744132, 18.07979032, 23.0884134 , 13.13709279, 16.80201863,
       13.43580038, 29.32286741, 25.04637334, 25.42545965, 16.96334059,
       16.85227864, 34.94961846, 16.59225971, 27.81460607, 22.34

In [25]:
np.savetxt('boston2.csv',y_pred,fmt='%10.10f',delimiter=',')