In [100]:
import pandas as pd
import numpy as np

In [178]:
df_training=np.genfromtxt('0000000000002419_training_ccpp_x_y_train.csv',delimiter=',')
#df_training.head()
x_train=df_training[:,:-1]
y_train=df_training[:,-1]



In [179]:
y_train

array([482.26, 446.94, 452.56, ..., 437.65, 459.97, 444.42])

In [180]:
from sklearn.preprocessing import StandardScaler
SS=StandardScaler()
x_train[:,:]=SS.fit_transform(x_train[:,:])
x_train

array([[-1.47827466e+00, -1.24764165e+00,  1.30221067e+00,
         7.58624590e-01],
       [ 2.89012041e-01,  3.06797549e-01,  6.61749044e-01,
        -4.46921842e-01],
       [-3.99975582e-01, -4.21012529e-01, -2.87207194e-01,
         3.75010552e-01],
       ...,
       [ 1.36062192e+00,  1.18048335e+00, -6.54382840e-01,
        -5.83682640e-01],
       [-4.36097263e-01,  9.29089763e-04,  7.84140927e-01,
        -6.59584883e-01],
       [ 1.40209496e+00,  6.07960340e-01, -4.31394890e-01,
        -1.73110573e+00]])

In [ ]:
def cost(x,y, m, c):
    total_cost = 0
    M = len(x)
    for i in range(M):
        x1 = x[i, :]
        y1 = y[i]
        total_cost += (1/M)*((y1 - (m*x1).sum() - c)**2)
    return total_cost

In [ ]:
def mc_calc(x,y, learning_rate, m , c):
    m_slope = list(0 for ni in range(x.shape[1]))
    c_slope = 0
    rows = len(x)
    a=0
    for i in range(rows):
        x1 = x[i, :]
        y1 = y[i]
        a=m*x1
        #print(a.shape)
        for j in range(x1.shape[0]):
            m_slope[j]+=(-2/rows)* (y1 - (a.sum(axis=0)) - c)*x1[j]
        c_slope += (-2/rows)* (y1 - (a.sum(axis=0)) - c)
    m_slope=np.array(m_slope)
    new_m = m - (learning_rate*m_slope)
    new_c = c - (learning_rate*c_slope)
    return new_m, new_c


In [ ]:
def gradient_descent(x,y, learning_rate, num_iterations):
    m=[0 for i in range(x.shape[1])] 
    c = 0
    for i in range(num_iterations):
        m, c = mc_calc(x,y, learning_rate, m , c)
        print(i, " Cost: ", cost(x,y, m, c))
    return m, c

In [ ]:
learning_rate = 0.1
num_iterations = 300
m, c = gradient_descent(x_train,y_train, learning_rate, num_iterations)
print(m, c)

In [181]:
df_test=np.genfromtxt('0000000000002419_test_ccpp_x_test.csv',delimiter=',')

In [182]:
df_test[:,:]=SS.fit_transform(df_test[:,:])
df_test


array([[-1.05179958, -0.9803295 ,  0.73940279,  1.20354042],
       [-1.03554677, -1.28089884, -0.09850361,  0.5680886 ],
       [ 0.97438468,  1.64050792, -1.29819445,  0.38358038],
       ...,
       [ 0.62359476,  0.94554072, -0.70944148,  1.27238677],
       [ 0.51117945, -0.91910241,  0.1216388 , -0.55754924],
       [ 0.27686804,  0.47003684,  0.97490397,  0.80216619]])

In [ ]:
y_pred=np.array((m*df_test).sum(axis=1))+c
y_pred

In [ ]:
np.savetxt('y_pred_ccpp.csv',y_pred,fmt='%10.10f',delimiter=',')

In [104]:
# changes are we pass m as array with last element as c in it.
# We will not have m_slope or c_slope as well, we will have another array whoch will start with all 0's and we will update 
# these values within this array.  

def step_gradient(X, Y, learning_rate, m):
    
    # m_slope = 0
    # c_slope = 0
    
    features = X.shape[1]
    mslope  = np.array([0.0 for i in range(features)])   # make sure we take numpy array here or else it will give typeerror.
    M = len(X)
    for i in range(M): # going through all data
        x = X[i, :]
        y = Y[i]
        
        # calculating m*x for a row here
        # this will return an array of mx.
        mx = m*x
        for j in range(features):
            mslope[j] +=   (-2/M)* (y - mx.sum(axis = 0) ) * x[j]  
    new_m = m - learning_rate*mslope
    m = new_m
    return m 

In [105]:
def gd(X, Y, learning_rate, num_iterations):
    m = [0 for i in range(X.shape[1])]
    for i in range(num_iterations):
        m= step_gradient(X,Y, learning_rate, m)
        print(i, 'Cost: ', cost(X, Y, m))
    return m


In [106]:
def cost(X, Y, m):
    total_cost = 0
    M = len(X)
    
    for i in range(M):
        x = X[i, :]
        y = Y[i]
        total_cost += (1/M) * ( y - (m*x).sum() )**2
    return total_cost

In [185]:
x_train = np.c_[x_train, np.ones(x_train.shape[0])]
df_test = np.c_[df_test, np.ones(df_test.shape[0])]

def run():
    #data = np.loadtxt("https://files.codingninjas.in/data-6984.csv", delimiter=",")
    learning_rate = 0.1
    num_iterations = 200
    
    # here we adding columns with all 1's for Generic Case.
    X = x_train
    Y = y_train
    #for i in X:
    #    i = np.append(i, 1.0)

    m = gd(X, Y, learning_rate, num_iterations)
    print(m, m[-1])# As last element of m is c.
    return m
    
    

In [186]:
m = run()

0 Cost:  132273.17028197853
1 Cost:  84643.21738144128
2 Cost:  54177.474227792685
3 Cost:  34683.656935452964
4 Cost:  22208.479529620818
5 Cost:  14224.382169986968
6 Cost:  9114.383468776608
7 Cost:  5843.781284088756
8 Cost:  3750.4051743364307
9 Cost:  2410.4727339052597
10 Cost:  1552.762193756394
11 Cost:  1003.6891423474597
12 Cost:  652.1571417929908
13 Cost:  427.06242464503333
14 Cost:  282.8969056987255
15 Cost:  190.5340535532469
16 Cost:  131.33178845157047
17 Cost:  93.35828546206275
18 Cost:  68.97644681535036
19 Cost:  53.297930953967374
20 Cost:  43.193704743608556
21 Cost:  36.66077597552082
22 Cost:  32.41688558517924
23 Cost:  29.641097514004986
24 Cost:  27.807765771435207
25 Cost:  26.58026504888727
26 Cost:  25.742971704330984
27 Cost:  25.157726328859923
28 Cost:  24.73596559178298
29 Cost:  24.42088326947476
30 Cost:  24.176010622787736
31 Cost:  23.977905690256787
32 Cost:  23.81147271061384
33 Cost:  23.6669651644581
34 Cost:  23.53806659977331
35 Cost:  23.

In [187]:
c = m[-1]
y_pred=np.array((m*df_test).sum(axis=1))

In [189]:
np.savetxt('y_pred_for_14.csv',y_pred,fmt='%10.10f',delimiter=',')