In [2]:
import numpy as np
a = np.random.randint(1,30, (5,6))
print(a)

[[ 5 16  6  7 22  6]
 [20  1 21 21 12 22]
 [16 21  7 23  1 16]
 [ 9 19  8 12 17  2]
 [18 14 15  9  3 21]]


In [5]:
## to get value > 20
bool_arr = a > 20  ## this will do element by element comparison of arr and give
                   ## true if the value is > 20 else it will give false.
                   ## And the result is returned as boolean array
print(bool_arr)   

[[False False False False  True False]
 [False False  True  True False  True]
 [False  True False  True False False]
 [False False False False False False]
 [False False False False False  True]]


In [6]:
## to extract value > 20.     Note: This will only work for numpy array and not for normal array.
ans = a[bool_arr]
print(a)

[[ 5 16  6  7 22  6]
 [20  1 21 21 12 22]
 [16 21  7 23  1 16]
 [ 9 19  8 12 17  2]
 [18 14 15  9  3 21]]


In [8]:
b = a
print(b)

[[ 5 16  6  7 22  6]
 [20  1 21 21 12 22]
 [16 21  7 23  1 16]
 [ 9 19  8 12 17  2]
 [18 14 15  9  3 21]]


In [10]:
## to update every value > 20 as 100.
b[bool_arr] = 100
print(b)  ## now we can see that every value which is greater than 20 is now 100.

[[  5  16   6   7 100   6]
 [ 20   1 100 100  12 100]
 [ 16 100   7 100   1  16]
 [  9  19   8  12  17   2]
 [ 18  14  15   9   3 100]]


In [16]:
## To update one array value in the next, the dimension must be same or it will
## give error.

## e.g.
c = np.random.randint(1,10, (2,2))
print(c)

print()

c_bool = np.array([[True, False],[False, True],[True, True]])
print(c_bool)

print()

print(c[c_bool])  ## this will throw error because c is 2x2  and  c_bool is 3x2  and for which 0th 
                  ## dimension for both doesnt match



[[1 4]
 [7 3]]

[[ True False]
 [False  True]
 [ True  True]]



IndexError: boolean index did not match indexed array along dimension 0; dimension is 2 but corresponding boolean dimension is 3

In [22]:
## To work over specific element in a 2d matrix.
print(b)

print()

## Now in this, we have to work on column 3 and update every value which is 99.
## for that we will create bool_arr which will work for every row and column 3.

bool_arr =  b[:, 3] == 99
print(bool_arr)

## Now to update the value of column 3 in b array, 

b[bool_arr, 3] = -1999   ## this will update -1999 to every value which is True in 
                         ## bool_arr in array b.
    
print(b)

## Working of update is we have passed row as bool_arr which means it will take index as 0 and 1
## which are true and for column, we have specified as 3, so it will update the value on that as -1999
##

[[  5  16   6   7 100   6]
 [ 20   1 100  99  12 100]
 [ 16 100   7  99   1  16]
 [  9  19   8  12  17   2]
 [ 18  14  15   9   3 100]]

[False  True  True False False]
[[    5    16     6     7   100     6]
 [   20     1   100 -1999    12   100]
 [   16   100     7 -1999     1    16]
 [    9    19     8    12    17     2]
 [   18    14    15     9     3   100]]
