## General Broadcasting Rules  
When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing (i.e. rightmost) dimensions and works its way left. Two dimensions are compatible when

they are equal, or

one of them is 1

If these conditions are not met, a ValueError: operands could not be broadcast together exception is thrown, indicating that the arrays have incompatible shapes. The size of the resulting array is the size that is not 1 along each axis of the inputs.

In [2]:
import numpy as np

x = np.random.randint(1,10,(3,3))
y = np.random.randint(1,10,(3,3))
print(x)
print(y)

[[3 2 3]
 [5 1 4]
 [7 7 6]]
[[4 4 5]
 [5 8 5]
 [4 3 4]]


In [3]:
ans = x - y
print(x - y)

[[-1 -2 -2]
 [ 0 -7 -1]
 [ 3  4  2]]


In [5]:
x = np.random.randint(1,10,(3,3))
y = np.random.randint(1,10,(3))
print(x)
print(y)

[[6 7 8]
 [7 6 5]
 [4 4 9]]
[4 3 7]


In [7]:
## as we cn see, one of them is of 3x3 dimension, and other is of just 3 which can be read  as 1x3
## Now what broadcasting does is that it makes element of y as 3x3 adding same row 3 times and then
## we get the answer below
## y matrix after broadcasting becomes [[4,3,7],[4,3,7],[4,3,7]]

ans = x - y  
print(ans)

[[ 2  4  1]
 [ 3  3 -2]
 [ 0  1  2]]


In [12]:
x = np.random.randint(1,10,(2,3))
y = np.random.randint(1,10,(3,2))
print(x)
print(y)



[[6 4 8]
 [7 8 2]]
[[3 3]
 [3 7]
 [5 5]]


In [16]:
## Now in this case, the x is of 2x3 and y is of 3x2
## It will throw error.


ans = x - y
print(ans)



ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [17]:
## to Solve it, we use transpose() on any one of it.

y = np.transpose(y)
ans = x - y
print(ans)

[[ 3  1  3]
 [ 4  1 -3]]


## Broadcasting Examples

1. If x = (3,1) and y = (3,3), we make x = (3x3) by adding two more columns. 
   Result is of (3x3) matrix
2. If x = (1,3) and y = (3,1), we make x = (3x3) by adding two more rows of same value
   and y = (3x3) by adding two more columns of same value.Result is of (3x3) matrix.
3. If x = (1x3) and y = (1), then we make x = (1x3) by adding three more columns.
   Result is of (1x3) matrix.
   
   We dont add or make matrix, the program automatically does it when one of the dimension is 1.