In [2]:
## numpy.arange 
## it Return evenly spaced values within a given interval.

## syntax : numpy.arange([start, ]stop, [step, ]dtype=None)


import numpy as np

b = np.arange(2, 10)
b



array([2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
b = np.arange(2, 20, 2)
b

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
## numpy.linespace
## Return evenly spaced numbers over a specified interval.
## Returns num evenly spaced samples, calculated over the interval [start, stop].
## The endpoint of the interval can optionally be excluded.

## numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

b = np.linspace(2,10)
b
print(b[1] - b[0])
print(b[3] - b[2])  ## to check if the step values are correct or not

0.16326530612244916
0.16326530612244916


In [10]:
b = np.linspace(2, 10,5, dtype = int) ## now in this case start is 2 and end is 10 and both are 
                                      ## included in the output unlike arange and range function.
b

array([ 2,  4,  6,  8, 10])

In [13]:
## checking other argument in linspace()

b = np.linspace(2, 10, 5,  dtype = int, endpoint = False)  ## third argument is no of samples
                                                           ## to generate which is 5, so 5 elements at
                                                           ## random will be printed from 2 to 10.
b  
## if we see, endpoint 10 is not included in the output because we 
## added argument endpoint = False.


array([2, 3, 5, 6, 8])

In [14]:
## difference between arange() and linspace() is in arange, we have control over number of
## steps value and in linspace, we have control over number of sample values.

In [16]:
b = np.identity(3)  ## as per the name, we will get identity matrix of nxn.It can only take 1 argument
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
b = np.eye(3,4)  ## it is same as above but it can take m and n i.e. 2 argument.
b 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [20]:
b = np.random.rand(3)   ## it will generate n random values.And it will be in range 0-1.
b

array([0.5492148 , 0.90155563, 0.75982893])

In [21]:
b = np.random.rand(2, 3)  ## this will create mxn matrix of random numbers.
b

array([[0.57042505, 0.3367904 , 0.07443341],
       [0.54943823, 0.70668046, 0.02455244]])

In [22]:
b = np.random.rand(10)* 10  ## this will give random values from range 1-10
                            ## to get values from 0 to 100, multiply it by 100
b  

array([0.65159353, 5.27366391, 2.2961122 , 9.62484838, 4.22168668,
       2.22807126, 1.76902176, 4.83596113, 4.9362047 , 3.52077769])