In [ ]:
## Numpy arrays are collection of pointers which points to four different attributes
## 1. data -> which represents reference to first byte of the array i.e. first element
## 2. shape -> which represents size of the array.
## 3. dtype -> which represents datatypes of elements of the array.
## 4. strides -> which represents number of bytes to be skipped to get to the next element.
##

In [5]:
import numpy as np
li = [1, 2, 3, 4, 5]
arr = np.array(li)

print(li)
print(arr)


[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [8]:
print(arr.data)
print(arr.shape)  ## it is a 1d array of size 5x1 so it shows (5, ) which means 5,1
print(arr.dtype)
print(arr.strides)  ## strides here shows no of bytes need to be skipped to move from one element
                    ## to the next.Which means each integer takes 4 or 8 bytes to store.


(5,)
int32
(4,)


In [9]:
## accessing element from numpy array
print(li[4])  ## accessing element at index 4

print(li[1:4])  ## slicing numpy array 

## Accessing values from 1d numpy array is as same as normal array but there is a slight 
## difference in 2d numpy array
 

5
[2, 3, 4]


In [2]:
li_2d = [[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]]
arr_2d = np.array(li_2d)

print(li_2d)
print(arr_2d)


[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [10]:
print(arr_2d.data)
print(arr_2d.shape) ## its a 4x4 array so it shows (4,4)
print(arr_2d.dtype)
print(arr_2d.strides)  ## it shows (16,4) in which first value indicates no of bytes to be skipped
                       ## to get to the next row. that means of we are at 5 and we want to move at 9,
                       ## we need to skip 16 bytes.
                       ## Second value indicates value needed to skip to move to the next element
                       ## at the second row.

(4, 4)
int32
(16, 4)


In [16]:
## accessing element from 2d numpy array

print(li_2d[2][1])
print(arr_2d[2][1])  ## accessing element at the 2nd row, 1st column

print(arr_2d[2,1])  ## this is the variation of numpy array where we pass row and col in 
                     ## only one bracket.
    

## slicing 2d numpy array

print(li_2d[1][:3])
print(arr_2d[1][:3])   ## slicing from row 1, col 0 to 3

print(arr_2d[1, :3])  ## variation in numpy array where we can pass the row and col in one bracket

print(arr_2d[0:3, 3])  ## slicing from col 3, row 0 to 3. This type of slicing works fine in 
                       ## numpy, but not in normal 2d list.

10
10
10
[5, 6, 7]
[5 6 7]
[5 6 7]
[ 4  8 12]


In [18]:
print(li_2d[0:3][3])  ## It is showing error.

IndexError: list index out of range

In [23]:
## explaination of the error

x = li_2d[0:3]
print(x)
y= x[2]
print(y) 

## for the expression print(li_2d[0:3][3]), it first gets the value of the part li_2d[0:3], which 
## fetches the data from index 0,1,2 and then it finds the answer from the index 0,1,2 but the 
## column is till 2, and we passed col as 3,
## so it shows indexerror.If we print value from index less than 3, we will get 
## answers.
## e.g.
print(li_2d[0:3][0])   ## using column as 0.
##It is better to use numpy for this type of problem.



[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
[9, 10, 11, 12]
[1, 2, 3, 4]


In [25]:
print(arr_2d[2:4, 1:3])
print(li_2d[2:4][1:3])

[[10 11]
 [14 15]]
[[13, 14, 15, 16]]


In [27]:
print(li_2d[2:4])

[[9, 10, 11, 12], [13, 14, 15, 16]]
