In [2]:
import numpy as np
li = [1,2,3,4,5]

a = np.random.randint(1,20,5)
b = np.random.randint(1,20,5)

print(li)
print(a)
print(b)


[1, 2, 3, 4, 5]
[18  1 18  8 15]
[19 15 16  3  5]


In [3]:
## To add 1 to each element of list and numpy array

## for list
li = [i+1 for i in li]
print(li)

## for numpy
a = a + 1
print(a)

[2, 3, 4, 5, 6]
[19  2 19  9 16]


In [5]:
## for adding elements of two numpy  array.
c = a + b
print(c)

[38 17 35 12 21]


In [8]:
## for subtracting elements of two numpy array
d = a - b
print(d)

[  0 -13   3   6  11]


In [9]:
## for multiplying elements of two numpy array
e = a * b
print(e)

[361  30 304  27  80]


In [10]:
## for division and floor division of two numpy array

f = a / b
g = a // b

print(f)
print(g)

[1.         0.13333333 1.1875     3.         3.2       ]
[1 0 1 3 3]


In [11]:
## for power 
h = a ** b
print(h)

[-306639989      32768 1637415489        729    1048576]


In [13]:
## some other numpy array function

print(a)

print(a.sum())
print(a.mean())  ## will give mean value of array a.
print(a.min())

print(a.argmin())  ## will give index of min element.
print(a.max())

print(a.argmax())  ## will give index of max value



[19  2 19  9 16]
65
13.0
2
1
19
0


In [14]:
print(a)
print(b)

[19  2 19  9 16]
[19 15 16  3  5]


In [15]:
## Comparison operators on numpy array
## it will do element by element comparison of numpy arrays and return output in the
## form of array

print(a>b)

print(a<b)

print(a == b)


[False False  True  True  True]
[False  True False False False]
[ True False False False False]


In [16]:
## Logical operators on numpy arrays
## will do operation element by element and give output 

print(np.logical_or(a, b))
print(np.logical_and(a, b))
print(np.logical_not(a))

[ True  True  True  True  True]
[ True  True  True  True  True]
[False False False False False]
