In [3]:
import numpy as np
a = np.array(['t','b','r','d','e', 'f','z','a'])
b = np.random.randint(1,20,8)

print(a)
print(b)


['t' 'b' 'r' 'd' 'e' 'f' 'z' 'a']
[ 2 13 11 18 16  8 16 10]


In [4]:
print(b > 10)  ## comparison operator, this will give every value > 10 as True in the array


[False  True  True  True  True False  True False]


In [7]:
## how to extract all elements > 10
bool_arr = b > 10
print(bool_arr) 

new_arr = b[bool_arr]  ## this will get all the values which are True in bool_arr
print(new_arr)

## the above code of new_arr can also be written as
 
new_arr = b[b > 10]   ## this will fetch out all the elements of b which are > 10.
                      ## Also note that this method is only for numpy arrays and not for
                      ## normal arrays.
print(new_arr)

[False  True  True  True  True False  True False]
[13 11 18 16 16]
[13 11 18 16 16]


In [9]:
newArr = b[(b > 10) & (b < 18)]  ## this will fetch all values b > 10 < 18. 
                                 ## also using 'and' will give error so we use 
                                 ## '&' instead of 'and'.
print(newArr)

[13 11 16 16]


In [11]:
print(b)
c = b
print(c)

[ 2 13 11 18 16  8 16 10]
[ 2 13 11 18 16  8 16 10]


In [13]:
c[:3] = 19    ## this will update all the elements from 0 to index 2 to 19
              ## Using same method in normal list will not work, we have to so the 
              ## we have to do the same operation on normal list in different way.
print(c)

[19 19 19 18 16  8 16 10]


In [15]:
print(c)
c[c> 15] = 100  ## this will update to all the values which are > 15 to 100.
print(c)

## Now in the first print, that will show the original value
## then it will check the condition i.e. > 15 and then it will update array in boolean
## value. Then it will update only those value to 100 which are True.

## The above method will not work for normal array,Infact any method in this page will not work
## For e.g lets do this for normal array

z = [1,2,3,4]   ## Normal array
z[z < 12] = 100  ## applying above method
print(z)   ## will show error.

[100 100 100 100 100   8 100  10]
[100 100 100 100 100   8 100  10]


TypeError: '<' not supported between instances of 'list' and 'int'

In [17]:
## using np.where()
## this function will give index of the values which is passed to them.

print(b)

print(b[b == 100])    ## this will actually print all the elements which are 100.

ind = np.where(b == 100)  ## this will give the index of 100 which are present in array in the form 
                          ## of array.
print(ind)

[100 100 100 100 100   8 100  10]
[100 100 100 100 100 100]
(array([0, 1, 2, 3, 4, 6], dtype=int64),)


In [19]:
print(a)
print(b)

print(a[ind])

['t' 'b' 'r' 'd' 'e' 'f' 'z' 'a']
[100 100 100 100 100   8 100  10]
['t' 'b' 'r' 'd' 'e' 'z']
