In [2]:
import numpy as np

a = [1,2,3]
b = np.array(a)  ## converting a list into numpy array
print(b)
print(type(b))   ## will show type of array


[1 2 3]
<class 'numpy.ndarray'>


In [3]:
a = [1,2,3,'5','a',4.5]   ## If we execute this, we can see that every element is in the
                           ## form of list.
                           ## Unlike other list, numpy can only contain data of homogenous 
                           ## element. Thats why, every data is converted into homogenous element.
                           ## This is the default behaviour of numpy.
                           ## We can convert the data into int by passing 'dtype' argument into 
                           ## function into below cell.
                        



b = np.array(a)  ## converting a list into numpy array
print(b)

['1' '2' '3' '5' 'a' '4.5']


In [5]:
a = [1,2,3,'5','a',4.5]
b = np.array(a, dtype = int)  ## this will throw error because we cannot convert a into int.
print(b)

ValueError: invalid literal for int() with base 10: 'a'

In [7]:
a = [1,2,3,'5',4.5]
b = np.array(a, dtype = int)  ## this will work fine and also we can convert the data into the 
                              ## float value by passing dtype = float and also str
print(b)

[1 2 3 5 4]


In [9]:
a = [1,2,3,'5',4.5]
b = np.array(a * 3)  ## in this we are repeating elements of a 3 times.

print(b)

['1' '2' '3' '5' '4.5' '1' '2' '3' '5' '4.5' '1' '2' '3' '5' '4.5']


In [11]:
## exploring other numpy functions.
b = np.ones(3, dtype = int)   ## this will create array of size 3 where every element is 1 
b                             ## of type int.

array([1, 1, 1])

In [13]:
b = np.zeros(3, dtype =int)   ## this will create array of size 3 where every element is 0 
b                             ## of type int.


array([0, 0, 0])

In [17]:
## creating 2d arrays
b = np.ones((2,3), dtype = int)  ## this will create 2d array of 2x3 of rows x columns.
b


array([[1, 1, 1],
       [1, 1, 1]])

In [20]:
## creating 2d arrays
b = np.zeros((3,4), dtype = int)  ## this will create 2d array of 2x3 of rows x columns.
b


array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [21]:
b = np.full(3)  ## here passing fill argument is obligatory.
b

TypeError: full() missing 1 required positional argument: 'fill_value'

In [23]:
b = np.full(3,5)  ## this will create array of size 3 with all three elements as fill value. i.e. 5.
b

array([5, 5, 5])

In [24]:
b = np.full((3,4), 4, dtype = float) ## will create 2d array of 3x4.
b

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])