In [1]:
## Open and read data file as specified in the question
## Print the required output in given format
import numpy as np
a = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
b = np.array(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
