In [1]:
import pandas as pd
import numpy as np

In [2]:
df_training=np.genfromtxt('0000000000002417_training_boston_x_y_train.csv',delimiter=',')
#df_training.head()
x_train=df_training[:,:-1]
y_train=df_training[:,-1]
x_train

array([[-0.40784991, -0.48772236, -1.2660231 , ..., -0.30309415,
         0.41057102, -1.09799011],
       [-0.40737368, -0.48772236,  0.24705682, ...,  0.1130321 ,
         0.29116915, -0.52047412],
       [ 0.1251786 , -0.48772236,  1.01599907, ...,  0.80657583,
        -3.79579542,  0.89107588],
       ...,
       [-0.40831101, -0.48772236,  0.24705682, ...,  0.1130321 ,
         0.33206621, -0.33404299],
       [-0.41061997, -0.48772236, -1.15221381, ..., -0.71922039,
         0.203235  , -0.74475218],
       [ 0.34290895, -0.48772236,  1.01599907, ...,  0.80657583,
         0.38787479, -1.35871335]])

In [ ]:
from sklearn.preprocessing import StandardScaler
SS=StandardScaler()
x_train[:,:]=SS.fit_transform(x_train[:,:])
x_train

In [3]:
def cost(x,y, m, c):
    total_cost = 0
    M = len(x)
    for i in range(M):
        x1 = x[i, :]
        y1 = y[i]
        total_cost += (1/M)*((y1 - (m*x1).sum() - c)**2)
    return total_cost

In [4]:
def mc_calc(x,y, learning_rate, m , c):
    m_slope = list(0 for ni in range(x.shape[1]))
    c_slope = 0
    rows = len(x)
    a=0
    for i in range(rows):
        x1 = x[i, :]
        y1 = y[i]
        a=m*x1
        #print(a.shape)
        for j in range(x1.shape[0]):
            m_slope[j]+=(-2/rows)* (y1 - (a.sum(axis=0)) - c)*x1[j]
        c_slope += (-2/rows)* (y1 - (a.sum(axis=0)) - c)
    m_slope=np.array(m_slope)
    new_m = m - (learning_rate*m_slope)
    new_c = c - (learning_rate*c_slope)
    return new_m, new_c


In [5]:
def gradient_descent(x,y, learning_rate, num_iterations):
    m=[0 for i in range(x.shape[1])] 
    c = 0
    for i in range(num_iterations):
        m, c = mc_calc(x,y, learning_rate, m , c)
        print(i, " Cost: ", cost(x,y, m, c))
    return m, c

In [12]:
learning_rate = 0.1
num_iterations = 500
m, c = gradient_descent(x_train,y_train, learning_rate, num_iterations)
print(m, c)

0  Cost:  374.24035597919686
1  Cost:  245.37909656079904
2  Cost:  165.10614192173668
3  Cost:  114.49508621191686
4  Cost:  82.43432664281798
5  Cost:  62.04170468831092
6  Cost:  49.0154746660482
7  Cost:  40.65519326019772
8  Cost:  35.259728350675914
9  Cost:  31.754121492629718
10  Cost:  29.457161634001743
11  Cost:  27.93600702214453
12  Cost:  26.914922412896377
13  Cost:  26.217802951980172
14  Cost:  25.731872822963105
15  Cost:  25.384699117718036
16  Cost:  25.129603525591076
17  Cost:  24.936384410518784
18  Cost:  24.785404792037365
19  Cost:  24.66381822190748
20  Cost:  24.56315514362143
21  Cost:  24.477776518190062
22  Cost:  24.403881200700226
23  Cost:  24.338867434896198
24  Cost:  24.28092114834845
25  Cost:  24.228749732407817
26  Cost:  24.181409300585187
27  Cost:  24.138192120101177
28  Cost:  24.098552859489228
29  Cost:  24.062059938191158
30  Cost:  24.028363158977225
31  Cost:  23.99717194248321
32  Cost:  23.968240497783352
33  Cost:  23.94135755771043
3

279  Cost:  23.466358272755336
280  Cost:  23.466350135475988
281  Cost:  23.4663422135219
282  Cost:  23.466334501194673
283  Cost:  23.466326992946687
284  Cost:  23.466319683377137
285  Cost:  23.46631256722834
286  Cost:  23.466305639381538
287  Cost:  23.46629889485374
288  Cost:  23.466292328793617
289  Cost:  23.466285936478403
290  Cost:  23.466279713310247
291  Cost:  23.466273654813055
292  Cost:  23.46626775662918
293  Cost:  23.466262014516293
294  Cost:  23.466256424344362
295  Cost:  23.466250982092696
296  Cost:  23.46624568384695
297  Cost:  23.46624052579643
298  Cost:  23.466235504231328
299  Cost:  23.46623061553986
300  Cost:  23.46622585620606
301  Cost:  23.466221222806805
302  Cost:  23.46621671200972
303  Cost:  23.466212320570474
304  Cost:  23.46620804533074
305  Cost:  23.466203883215677
306  Cost:  23.46619983123189
307  Cost:  23.466195886465115
308  Cost:  23.466192046078245
309  Cost:  23.466188307309306
310  Cost:  23.466184667469353
311  Cost:  23.46618

In [13]:
df_test=np.genfromtxt('0000000000002417_test_boston_x_test.csv',delimiter=',')
df_test

array([[ 2.91816626, -0.48772236,  1.01599907, ...,  0.80657583,
        -1.59755122,  1.04106182],
       [-0.40339151, -0.48772236,  0.40609801, ..., -1.13534664,
         0.44105193, -0.89473812],
       [-0.4131781 , -0.48772236,  0.11573841, ...,  1.17646583,
         0.44105193, -0.50084979],
       ...,
       [-0.41001449,  2.08745172, -1.37837329, ..., -0.0719129 ,
         0.39094481, -0.68167397],
       [-0.40317611, -0.48772236, -0.37597609, ...,  1.13022958,
         0.34007019,  0.20142086],
       [-0.13356344, -0.48772236,  1.2319449 , ..., -1.73641788,
        -2.93893082,  0.48877712]])

In [ ]:
df_test[:,:]=SS.fit_transform(df_test[:,:])
df_test


In [14]:
y_pred=np.array((m*df_test).sum(axis=1))+c
y_pred

array([12.43305461, 29.03276311, 22.3717741 , 24.47704949, 20.60304646,
        2.72575331, 30.39871373, 24.86084904, 18.65761314, 23.53985262,
       24.11394005, 17.71177594, 17.44164037, 21.65424892, 42.31187041,
       23.85043266, 24.47570241, 27.539682  , 20.23670118, 31.1524864 ,
       23.78384683, 25.00949304, 33.95749751, 36.43480907, 32.041559  ,
       16.71262908, 23.47207502, 32.93967198, 25.17977231, 33.71015341,
       16.8861749 , 26.02847489, 23.27064274, 25.47742472, 15.009428  ,
       29.58617193, 26.24822188, 20.37369403, 24.43593577,  9.44715852,
        8.380489  , 29.01359382, 29.59127303, 19.75801938, 20.37163303,
        3.14415801, 39.52410253, 25.71742342, 30.37577819, 16.79432253,
       17.89057148, 41.02421716, 17.57218034, 20.89762591, 15.59869186,
       21.4132645 , 18.45434406, 23.15584186, 13.67278925, 17.23542172,
       15.0274139 , 29.15132801, 25.17269239, 25.49746067, 17.21142936,
       17.42920421, 34.70357605, 17.01316245, 27.10641654, 22.54

In [15]:
np.savetxt('y_pred_boston',y_pred,fmt='%10.20f',delimiter=',')