In [1]:
import pandas as pd
import numpy as np

In [2]:
df_training=np.genfromtxt('0000000000002419_training_ccpp_x_y_train.csv',delimiter=',')
#df_training.head()
x_train=df_training[:,:-1]
y_train=df_training[:,-1]
x_train

array([[   8.58,   38.38, 1021.03,   84.37],
       [  21.79,   58.2 , 1017.21,   66.74],
       [  16.64,   48.92, 1011.55,   78.76],
       ...,
       [  29.8 ,   69.34, 1009.36,   64.74],
       [  16.37,   54.3 , 1017.94,   63.63],
       [  30.11,   62.04, 1010.69,   47.96]])

In [3]:
y_train

array([482.26, 446.94, 452.56, ..., 437.65, 459.97, 444.42])

In [4]:
from sklearn.preprocessing import StandardScaler
SS=StandardScaler()
x_train[:,:]=SS.fit_transform(x_train[:,:])
x_train

array([[-1.47827466e+00, -1.24764165e+00,  1.30221067e+00,
         7.58624590e-01],
       [ 2.89012041e-01,  3.06797549e-01,  6.61749044e-01,
        -4.46921842e-01],
       [-3.99975582e-01, -4.21012529e-01, -2.87207194e-01,
         3.75010552e-01],
       ...,
       [ 1.36062192e+00,  1.18048335e+00, -6.54382840e-01,
        -5.83682640e-01],
       [-4.36097263e-01,  9.29089763e-04,  7.84140927e-01,
        -6.59584883e-01],
       [ 1.40209496e+00,  6.07960340e-01, -4.31394890e-01,
        -1.73110573e+00]])

In [5]:
def cost(x,y, m, c):
    total_cost = 0
    M = len(x)
    for i in range(M):
        x1 = x[i, :]
        y1 = y[i]
        total_cost += (1/M)*((y1 - (m*x1).sum() - c)**2)
    return total_cost

In [6]:
def mc_calc(x,y, learning_rate, m , c):
    m_slope = list(0 for ni in range(x.shape[1]))
    c_slope = 0
    rows = len(x)
    a=0
    for i in range(rows):
        x1 = x[i, :]
        y1 = y[i]
        a=m*x1
        #print(a.shape)
        for j in range(x1.shape[0]):
            m_slope[j]+=(-2/rows)* (y1 - (a.sum(axis=0)) - c)*x1[j]
        c_slope += (-2/rows)* (y1 - (a.sum(axis=0)) - c)
    m_slope=np.array(m_slope)
    new_m = m - (learning_rate*m_slope)
    new_c = c - (learning_rate*c_slope)
    return new_m, new_c


In [7]:
def gradient_descent(x,y, learning_rate, num_iterations):
    m=[0 for i in range(x.shape[1])] 
    c = 0
    for i in range(num_iterations):
        m, c = mc_calc(x,y, learning_rate, m , c)
        print(i, " Cost: ", cost(x,y, m, c))
    return m, c

In [9]:
learning_rate = 0.1
num_iterations = 300
m, c = gradient_descent(x_train,y_train, learning_rate, num_iterations)
print(m, c)

0  Cost:  132273.17028197853
1  Cost:  84643.2173814413
2  Cost:  54177.47422779268
3  Cost:  34683.65693545296
4  Cost:  22208.4795296208
5  Cost:  14224.382169986959
6  Cost:  9114.3834687766
7  Cost:  5843.781284088749
8  Cost:  3750.405174336423
9  Cost:  2410.472733905253
10  Cost:  1552.7621937563936
11  Cost:  1003.6891423474597
12  Cost:  652.1571417929908
13  Cost:  427.06242464503106
14  Cost:  282.89690569872374
15  Cost:  190.53405355324563
16  Cost:  131.33178845156934
17  Cost:  93.35828546206177
18  Cost:  68.97644681534966
19  Cost:  53.297930953966734
20  Cost:  43.19370474360805
21  Cost:  36.66077597552081
22  Cost:  32.41688558517922
23  Cost:  29.64109751400498
24  Cost:  27.8077657714352
25  Cost:  26.580265048887277
26  Cost:  25.74297170433098
27  Cost:  25.157726328859912
28  Cost:  24.73596559178298
29  Cost:  24.420883269474757
30  Cost:  24.17601062278773
31  Cost:  23.97790569025679
32  Cost:  23.81147271061384
33  Cost:  23.666965164458098
34  Cost:  23.53

273  Cost:  20.911888438100082
274  Cost:  20.91188281973395
275  Cost:  20.911877427732225
276  Cost:  20.91187225297489
277  Cost:  20.91186728670899
278  Cost:  20.91186252053455
279  Cost:  20.91185794638973
280  Cost:  20.911853556537633
281  Cost:  20.911849343553385
282  Cost:  20.911845300310453
283  Cost:  20.91184141997034
284  Cost:  20.911837695969602
285  Cost:  20.91183412200914
286  Cost:  20.91183069204393
287  Cost:  20.911827400272394
288  Cost:  20.911824241126638
289  Cost:  20.91182120926329
290  Cost:  20.911818299553975
291  Cost:  20.91181550707702
292  Cost:  20.911812827109397
293  Cost:  20.91181025511807
294  Cost:  20.911807786752377
295  Cost:  20.91180541783739
296  Cost:  20.911803144366424
297  Cost:  20.911800962493665
298  Cost:  20.91179886852896
299  Cost:  20.911796858930177
[-14.8860394   -2.90663084   0.35284624  -2.33686005] 454.4312931995539


In [10]:
df_test=np.genfromtxt('0000000000002419_test_ccpp_x_test.csv',delimiter=',')
df_test

array([[  11.95,   42.03, 1017.58,   90.89],
       [  12.07,   38.25, 1012.67,   81.66],
       [  26.91,   74.99, 1005.64,   78.98],
       ...,
       [  24.32,   66.25, 1009.09,   91.89],
       [  23.49,   42.8 , 1013.96,   65.31],
       [  21.76,   60.27, 1018.96,   85.06]])

In [11]:
df_test[:,:]=SS.fit_transform(df_test[:,:])
df_test


array([[-1.05179958, -0.9803295 ,  0.73940279,  1.20354042],
       [-1.03554677, -1.28089884, -0.09850361,  0.5680886 ],
       [ 0.97438468,  1.64050792, -1.29819445,  0.38358038],
       ...,
       [ 0.62359476,  0.94554072, -0.70944148,  1.27238677],
       [ 0.51117945, -0.91910241,  0.1216388 , -0.55754924],
       [ 0.27686804,  0.47003684,  0.97490397,  0.80216619]])

In [12]:
y_pred=np.array((m*df_test).sum(axis=1))+c
y_pred

array([470.38626915, 472.20728306, 433.80377687, ..., 439.17638571,
       450.83918145, 447.41304217])

In [13]:
np.savetxt('y_pred_ccpp',y_pred,fmt='%10.10f',delimiter=',')