### By cross validation,
what we mean is lets say there is an algorithm, and we have this classifier, which we want to train.  
And lets say there is some parameter p that we need to adjust.  
We need to choose the value for p.  
So how do we decide p?  
So we can look at the score of trainng data itself, passing the training dataand we can see  how well this classifier is working and choose our p accordingly.  
The problem with that is it might lead to overfitting because we might choose a value of p for which the training error is very less.  
But thats not what we want.  
The other option is why dont we pass the testing data to see what is the best value of p.  
The problem with that approach is if we are going to use our testing data to decide the value of p, that basically means that you are using your testing data to actually fit your model to dcide the parameters of your model. And thats again something that we dont want to do we want to make sure that your testing data is just for testing.  
So we are stuck with the fact that using testing kind of violates the basic rules of whatever we haeve learned that we want to test on the test data to figure out how good or bad we are performing, and the problem with doing it on training data is putting that p to a value which will basically lead to a low training error, but high testing error.  
So what we do is we use CROSS VALIDATION.  
It means we have our training data, lets split the training data into k parts, lets train our classifier using k-1 parts of the data, and test on the remaining part. In this we have split the training data, in this we have not used the test data anywhere. So first we do it on k-1 and then test it on last element and then we do this for all k subsets.  
So we run this k times,where we are using k-1 to train, and the rest 1 which is left for testing and then we are doing this k times. And then we can find out overall average score by doing this operation.   
So we can try doing this again and again, for different values of p, and the overall score will be, lets say p = 1, and we run cross validation 10 times if our k is 10, so if we run it 10 times, we will get 10 scores, and we will take the average of these scores.  
Similarly we can try it for p = 2, p = 3, and this way we can figure it out the best value of p at which we are getting the best score.  

Now how it is done in sklearn, 

In [1]:
import numpy as np
from sklearn  import datasets
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [2]:
iris = datasets.load_iris()

In [3]:
xtrain, xtest, ytrain, ytest = train_test_split(iris.data, iris.target, test_size = 0.2)

In [4]:
## so we are using cross_val_score, 
## estimator = is the classifier that we want to fit on variuos types.
## group = if we by ourself pass what group each data belongs to for eg, we want to make 3 groups and training data is x, 
##         so lets say the 0th row goes to group a, 2nd to b, 3rd to a, 4th to c, and so on. Then we can pass array of size of 
##         number of samplesand pass which datapoint belongs to which group.  
##         We will not use this generally, we want it to be a randomshufffle but in case we want to do it, we willdecide how to 
##         make this k subsets.  
## cv = cv is how exactly we make that split how exactly we generate the cross validation subsets.  
##      Most standard one is k fold we will use that.
## njobs = It means if we want to do some parallel processing, we can do it if our estimators fit function requiressome extra 
##         parameters.
## fit_parms = If we want to pass some extra parameters apart from x and y we use this.


In [5]:
## We use linear regression as fit for now.
clf = LinearRegression()


In [6]:
## we now pass training data and testing data. 
cross_val_score(clf, xtrain, ytrain)

## this is the score. It used 5 folds.It splitted data into 5 parts and we take avg of these score to see how good our 
## classifier is performing.

array([0.89427614, 0.87888815, 0.92393884, 0.95307551, 0.92710904])

In [7]:
##  one thing we can do is we can pass cv parameter in cross_va_score and pass the kfold object and we can do what we want.
## we can check the list of things we can do with kfold documentation.
## insttead of passing the training data, we can pass whole iris data and see what happens
cross_val_score(clf, iris.data, iris.target)

## we can see the score is zero in 3 places. 
## this is happening coz iris has 150 datasets the forst 50 belongs to class 0, second 50 belongs to class 1 and last 50 to 
## class 2.
## And that is how the data is split.  
## If we use 3 folds with shuffle = False, that means the first time we trained, we trained first 100 and tested on last 50.
## So obviously we get the score to be 0. 
## In our training data we dont have any object for class 2, but we have class 2 on training.  


array([0.        , 0.85124923, 0.        , 0.76155439, 0.        ])

In [8]:
## in this case we use cv object. 
from sklearn.model_selection import KFold
cross_val_score(clf, iris.data, iris.target, cv = KFold(3, True, 0 ))
## Here we put the no of splits to 3, shuffle is True and random_state = 0.

## Now we get the good score.

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:67: FutureWarning: Pass shuffle=True, random_state=0 as keyword args. From version 0.25 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.25 "


array([0.90322728, 0.92527008, 0.94214064])