In [1]:
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn import model_selection
from io import StringIO
from sklearn.linear_model import LinearRegression
from sklearn import preprocessing
from sklearn import datasets
from sklearn.linear_model import LogisticRegression
import os
os.listdir()

['.ipynb_checkpoints',
 '0000000000002429_test_titanic_x_test.csv',
 '0000000000002429_training_titanic_x_y_train.csv',
 'Logistic Regression - Titanic Dataset-Copy1.ipynb',
 'Logistic Regression - Titanic Dataset.ipynb',
 'LRPredictions',
 'LRPredictions2']

In [2]:
train = pd.read_csv('0000000000002429_training_titanic_x_y_train.csv')
test = pd.read_csv('0000000000002429_test_titanic_x_test.csv')

In [3]:
train.describe()

Pclass         Age       SibSp       Parch        Fare    Survived
count  668.000000  536.000000  668.000000  668.000000  668.000000  668.000000
mean     2.296407   29.700560    0.528443    0.407186   32.064552    0.402695
std      0.831638   14.240257    1.080327    0.854695   45.320835    0.490808
min      1.000000    0.670000    0.000000    0.000000    0.000000    0.000000
25%      2.000000   21.000000    0.000000    0.000000    7.925000    0.000000
50%      3.000000   29.000000    0.000000    0.000000   14.750000    0.000000
75%      3.000000   38.250000    1.000000    0.000000   31.275000    1.000000
max      3.000000   80.000000    8.000000    6.000000  512.329200    1.000000

In [4]:
train.head()

Pclass                                            Name     Sex   Age  \
0       2   Weisz, Mrs. Leopold (Mathilde Francoise Pede)  female  29.0   
1       3               Williams, Mr. Howard Hugh "Harry"    male   NaN   
2       2  Morley, Mr. Henry Samuel ("Mr Henry Marshall")    male  39.0   
3       3     Palsson, Mrs. Nils (Alma Cornelia Berglund)  female  29.0   
4       3                          Sutehall, Mr. Henry Jr    male  25.0   

   SibSp  Parch           Ticket    Fare Cabin Embarked  Survived  
0      1      0           228414  26.000   NaN        S         1  
1      0      0         A/5 2466   8.050   NaN        S         0  
2      0      0           250655  26.000   NaN        S         0  
3      0      4           349909  21.075   NaN        S         0  
4      0      0  SOTON/OQ 392076   7.050   NaN        S         0

In [5]:
test.head()

Pclass                                               Name     Sex   Age  \
0       2                     Davies, Master. John Morgan Jr    male   8.0   
1       1                        Leader, Dr. Alice (Farnham)  female  49.0   
2       3                            Kilgannon, Mr. Thomas J    male   NaN   
3       2  Jacobsohn, Mrs. Sidney Samuel (Amy Frances Chr...  female  24.0   
4       1                          McGough, Mr. James Robert    male  36.0   

   SibSp  Parch      Ticket     Fare Cabin Embarked  
0      1      1  C.A. 33112  36.7500   NaN        S  
1      0      0       17465  25.9292   D17        S  
2      0      0       36865   7.7375   NaN        Q  
3      2      1      243847  27.0000   NaN        S  
4      0      0    PC 17473  26.2875   E25        S

In [6]:
train.shape

(668, 11)

In [7]:
train.isna().sum()


Pclass        0
Name          0
Sex           0
Age         132
SibSp         0
Parch         0
Ticket        0
Fare          0
Cabin       514
Embarked      1
Survived      0
dtype: int64

In [8]:
train['Embarked'].value_counts()


S    484
C    133
Q     50
Name: Embarked, dtype: int64

In [ ]:
# onehotencoding, lableencoder
# Embarked, Sex = labelencoder.
## drop Name,Ticket, Cabin
## mean = age.

In [9]:
from sklearn.preprocessing import OneHotEncoder

label_encoder = preprocessing.LabelEncoder()
onhot_encoder= OneHotEncoder(sparse = False)

In [10]:
emb = train['Pclass']
emb = emb.to_numpy()
emb = emb.reshape(len(emb), 1)
embs = onhot_encoder.fit_transform(emb)
embs

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       ...,
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [11]:
train['Embarked'] = train['Embarked'].astype(str)
train['Embarked'] = label_encoder.fit_transform(train['Embarked'])
train['Embarked'].unique()



array([2, 0, 1, 3])

In [12]:
re = train['Embarked'].to_numpy()
re = re.reshape(len(train['Embarked']), 1)
enc = onhot_encoder.fit_transform(re)


In [13]:
col = ['1', '2', '3']
df5 = pd.DataFrame(embs, columns = col)
df5['index'] = df5.index

In [14]:
train['Sex'] = label_encoder.fit_transform(train['Sex'])

In [15]:
sex = train['Sex'].to_numpy()
sex = sex.reshape(len(train['Sex']), 1)
sex1 = onhot_encoder.fit_transform(sex)
sex1

array([[1., 0.],
       [0., 1.],
       [0., 1.],
       ...,
       [0., 1.],
       [1., 0.],
       [1., 0.]])

In [16]:
meanage = train['Age'].mean()

In [17]:
meanage = int(meanage)


In [18]:
col1 = ['Male', 'Female']
col2 = ['S', 'C', 'Q', 'Q1']

In [19]:
df1 = pd.DataFrame(enc, columns= col2)
df2 = pd.DataFrame(sex1, columns = col1)



In [20]:
df2

Male  Female
0     1.0     0.0
1     0.0     1.0
2     0.0     1.0
3     1.0     0.0
4     0.0     1.0
..    ...     ...
663   1.0     0.0
664   0.0     1.0
665   0.0     1.0
666   1.0     0.0
667   1.0     0.0

[668 rows x 2 columns]

In [21]:
train["Age"] = train['Age'].fillna(meanage)


In [22]:
train

Pclass                                            Name  Sex   Age  SibSp  \
0         2   Weisz, Mrs. Leopold (Mathilde Francoise Pede)    0  29.0      1   
1         3               Williams, Mr. Howard Hugh "Harry"    1  29.0      0   
2         2  Morley, Mr. Henry Samuel ("Mr Henry Marshall")    1  39.0      0   
3         3     Palsson, Mrs. Nils (Alma Cornelia Berglund)    0  29.0      0   
4         3                          Sutehall, Mr. Henry Jr    1  25.0      0   
..      ...                                             ...  ...   ...    ...   
663       2                             Ilett, Miss. Bertha    0  17.0      0   
664       3                        Morrow, Mr. Thomas Rowan    1  29.0      0   
665       3                                   Bing, Mr. Lee    1  32.0      0   
666       3                     Strandberg, Miss. Ida Sofia    0  22.0      0   
667       3                  Murphy, Miss. Katherine "Kate"    0  29.0      1   

     Parch           Ticket     Fare Cabin  Embarked  Survived  
0        0           228414  26.0000   NaN         2         1  
1        0         A/5 2466   8.0500   NaN         2         0  
2        0           250655  26.0000   NaN         2         0  
3        4           349909  21.0750   NaN         2         0  
4        0  SOTON/OQ 392076   7.0500   NaN         2         0  
..     ...              ...      ...   ...       ...       ...  
663      0       SO/C 14885  10.5000   NaN         2         1  
664      0           372622   7.7500   NaN         1         0  
665      0             1601  56.4958   NaN         2         1  
666      0             7553   9.8375   NaN         2         0  
667      0           367230  15.5000   NaN         1         1  

[668 rows x 11 columns]

In [23]:
train = train.drop(['Name', 'Ticket', 'Cabin'], axis= 1)

In [24]:
train

Pclass  Sex   Age  SibSp  Parch     Fare  Embarked  Survived
0         2    0  29.0      1      0  26.0000         2         1
1         3    1  29.0      0      0   8.0500         2         0
2         2    1  39.0      0      0  26.0000         2         0
3         3    0  29.0      0      4  21.0750         2         0
4         3    1  25.0      0      0   7.0500         2         0
..      ...  ...   ...    ...    ...      ...       ...       ...
663       2    0  17.0      0      0  10.5000         2         1
664       3    1  29.0      0      0   7.7500         1         0
665       3    1  32.0      0      0  56.4958         2         1
666       3    0  22.0      0      0   9.8375         2         0
667       3    0  29.0      1      0  15.5000         1         1

[668 rows x 8 columns]

In [25]:
train = train.drop(["Embarked", 'Sex'], axis = 1)

In [26]:
train

Pclass   Age  SibSp  Parch     Fare  Survived
0         2  29.0      1      0  26.0000         1
1         3  29.0      0      0   8.0500         0
2         2  39.0      0      0  26.0000         0
3         3  29.0      0      4  21.0750         0
4         3  25.0      0      0   7.0500         0
..      ...   ...    ...    ...      ...       ...
663       2  17.0      0      0  10.5000         1
664       3  29.0      0      0   7.7500         0
665       3  32.0      0      0  56.4958         1
666       3  22.0      0      0   9.8375         0
667       3  29.0      1      0  15.5000         1

[668 rows x 6 columns]

In [27]:
# train = pd.merge(train, df1, on = index)
# train
df1['index'] = df1.index
train['index'] = train.index

In [28]:
train = pd.merge(train, df1, on = 'index')

In [29]:
df2['index'] = df2.index

In [30]:
train = pd.merge(train, df2, on='index')

In [31]:
train

Pclass   Age  SibSp  Parch     Fare  Survived  index    S    C    Q   Q1  \
0         2  29.0      1      0  26.0000         1      0  0.0  0.0  1.0  0.0   
1         3  29.0      0      0   8.0500         0      1  0.0  0.0  1.0  0.0   
2         2  39.0      0      0  26.0000         0      2  0.0  0.0  1.0  0.0   
3         3  29.0      0      4  21.0750         0      3  0.0  0.0  1.0  0.0   
4         3  25.0      0      0   7.0500         0      4  0.0  0.0  1.0  0.0   
..      ...   ...    ...    ...      ...       ...    ...  ...  ...  ...  ...   
663       2  17.0      0      0  10.5000         1    663  0.0  0.0  1.0  0.0   
664       3  29.0      0      0   7.7500         0    664  0.0  1.0  0.0  0.0   
665       3  32.0      0      0  56.4958         1    665  0.0  0.0  1.0  0.0   
666       3  22.0      0      0   9.8375         0    666  0.0  0.0  1.0  0.0   
667       3  29.0      1      0  15.5000         1    667  0.0  1.0  0.0  0.0   

     Male  Female  
0     1.0     0.0  
1     0.0     1.0  
2     0.0     1.0  
3     1.0     0.0  
4     0.0     1.0  
..    ...     ...  
663   1.0     0.0  
664   0.0     1.0  
665   0.0     1.0  
666   1.0     0.0  
667   1.0     0.0  

[668 rows x 13 columns]

In [32]:
train = pd.merge(train, df5, on= 'index')

In [33]:
Y = train['Survived']

In [34]:
train = train.drop(['Survived', 'index', 'Pclass'], axis = 1)

In [35]:
train

Age  SibSp  Parch     Fare    S    C    Q   Q1  Male  Female    1    2  \
0    29.0      1      0  26.0000  0.0  0.0  1.0  0.0   1.0     0.0  0.0  1.0   
1    29.0      0      0   8.0500  0.0  0.0  1.0  0.0   0.0     1.0  0.0  0.0   
2    39.0      0      0  26.0000  0.0  0.0  1.0  0.0   0.0     1.0  0.0  1.0   
3    29.0      0      4  21.0750  0.0  0.0  1.0  0.0   1.0     0.0  0.0  0.0   
4    25.0      0      0   7.0500  0.0  0.0  1.0  0.0   0.0     1.0  0.0  0.0   
..    ...    ...    ...      ...  ...  ...  ...  ...   ...     ...  ...  ...   
663  17.0      0      0  10.5000  0.0  0.0  1.0  0.0   1.0     0.0  0.0  1.0   
664  29.0      0      0   7.7500  0.0  1.0  0.0  0.0   0.0     1.0  0.0  0.0   
665  32.0      0      0  56.4958  0.0  0.0  1.0  0.0   0.0     1.0  0.0  0.0   
666  22.0      0      0   9.8375  0.0  0.0  1.0  0.0   1.0     0.0  0.0  0.0   
667  29.0      1      0  15.5000  0.0  1.0  0.0  0.0   1.0     0.0  0.0  0.0   

       3  
0    0.0  
1    1.0  
2    0.0  
3    1.0  
4    1.0  
..   ...  
663  0.0  
664  1.0  
665  1.0  
666  1.0  
667  1.0  

[668 rows x 13 columns]

In [36]:
 
## fitting data
clf = LogisticRegression()

In [37]:
train = train.to_numpy()

In [38]:
clf.fit(train, Y)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [39]:
clf.score(train, Y)

## gave a good score but not the best, so we try again.

0.7994011976047904

## For testing Data

In [40]:
from sklearn.preprocessing import OneHotEncoder

label_encoder = preprocessing.LabelEncoder()
onhot_encoder= OneHotEncoder(sparse = False)

In [41]:
test 

Pclass                                               Name     Sex   Age  \
0         2                     Davies, Master. John Morgan Jr    male   8.0   
1         1                        Leader, Dr. Alice (Farnham)  female  49.0   
2         3                            Kilgannon, Mr. Thomas J    male   NaN   
3         2  Jacobsohn, Mrs. Sidney Samuel (Amy Frances Chr...  female  24.0   
4         1                          McGough, Mr. James Robert    male  36.0   
..      ...                                                ...     ...   ...   
218       3                        Lindqvist, Mr. Eino William    male  20.0   
219       1                  Butt, Major. Archibald Willingham    male  45.0   
220       1  Penasco y Castellana, Mrs. Victor de Satode (M...  female  17.0   
221       3                   Holm, Mr. John Fredrik Alexander    male  43.0   
222       2           Navratil, Mr. Michel ("Louis M Hoffman")    male  36.5   

     SibSp  Parch             Ticket      Fare Cabin Embarked  
0        1      1         C.A. 33112   36.7500   NaN        S  
1        0      0              17465   25.9292   D17        S  
2        0      0              36865    7.7375   NaN        Q  
3        2      1             243847   27.0000   NaN        S  
4        0      0           PC 17473   26.2875   E25        S  
..     ...    ...                ...       ...   ...      ...  
218      1      0  STON/O 2. 3101285    7.9250   NaN        S  
219      0      0             113050   26.5500   B38        S  
220      1      0           PC 17758  108.9000   C65        C  
221      0      0             C 7075    6.4500   NaN        S  
222      0      2             230080   26.0000    F2        S  

[223 rows x 10 columns]

In [42]:
p = test['Pclass']
p =  p.to_numpy()
p = p.reshape(len(p), 1)
ps = onhot_encoder.fit_transform(p)
ps

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0

In [43]:
df6 = pd.DataFrame(ps, columns = col)
df6['index'] = df6.index
df6

1    2    3  index
0    0.0  1.0  0.0      0
1    1.0  0.0  0.0      1
2    0.0  0.0  1.0      2
3    0.0  1.0  0.0      3
4    1.0  0.0  0.0      4
..   ...  ...  ...    ...
218  0.0  0.0  1.0    218
219  1.0  0.0  0.0    219
220  1.0  0.0  0.0    220
221  0.0  0.0  1.0    221
222  0.0  1.0  0.0    222

[223 rows x 4 columns]

In [44]:
test['Embarked'] = test['Embarked'].astype(str)
test['Embarked'] = label_encoder.fit_transform(test['Embarked'])
test['Embarked'].unique()



array([2, 1, 0, 3])

In [45]:
res = test['Embarked'].to_numpy()
res = res.reshape(len(res), 1)
enc = onhot_encoder.fit_transform(res)


In [46]:
test['Sex'] = label_encoder.fit_transform(test['Sex'])

In [47]:
sex = test['Sex'].to_numpy()
sex = sex.reshape(len(test['Sex']), 1)
sex1 = onhot_encoder.fit_transform(sex)
sex1


array([[0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.

In [48]:
test

Pclass                                               Name  Sex   Age  \
0         2                     Davies, Master. John Morgan Jr    1   8.0   
1         1                        Leader, Dr. Alice (Farnham)    0  49.0   
2         3                            Kilgannon, Mr. Thomas J    1   NaN   
3         2  Jacobsohn, Mrs. Sidney Samuel (Amy Frances Chr...    0  24.0   
4         1                          McGough, Mr. James Robert    1  36.0   
..      ...                                                ...  ...   ...   
218       3                        Lindqvist, Mr. Eino William    1  20.0   
219       1                  Butt, Major. Archibald Willingham    1  45.0   
220       1  Penasco y Castellana, Mrs. Victor de Satode (M...    0  17.0   
221       3                   Holm, Mr. John Fredrik Alexander    1  43.0   
222       2           Navratil, Mr. Michel ("Louis M Hoffman")    1  36.5   

     SibSp  Parch             Ticket      Fare Cabin  Embarked  
0        1      1         C.A. 33112   36.7500   NaN         2  
1        0      0              17465   25.9292   D17         2  
2        0      0              36865    7.7375   NaN         1  
3        2      1             243847   27.0000   NaN         2  
4        0      0           PC 17473   26.2875   E25         2  
..     ...    ...                ...       ...   ...       ...  
218      1      0  STON/O 2. 3101285    7.9250   NaN         2  
219      0      0             113050   26.5500   B38         2  
220      1      0           PC 17758  108.9000   C65         0  
221      0      0             C 7075    6.4500   NaN         2  
222      0      2             230080   26.0000    F2         2  

[223 rows x 10 columns]

In [49]:
meanage = test['Age'].mean()

In [50]:
meanage = int(meanage)

In [51]:
meanage

29

In [52]:
test["Age"] = test['Age'].fillna(meanage)


In [53]:
test

Pclass                                               Name  Sex   Age  \
0         2                     Davies, Master. John Morgan Jr    1   8.0   
1         1                        Leader, Dr. Alice (Farnham)    0  49.0   
2         3                            Kilgannon, Mr. Thomas J    1  29.0   
3         2  Jacobsohn, Mrs. Sidney Samuel (Amy Frances Chr...    0  24.0   
4         1                          McGough, Mr. James Robert    1  36.0   
..      ...                                                ...  ...   ...   
218       3                        Lindqvist, Mr. Eino William    1  20.0   
219       1                  Butt, Major. Archibald Willingham    1  45.0   
220       1  Penasco y Castellana, Mrs. Victor de Satode (M...    0  17.0   
221       3                   Holm, Mr. John Fredrik Alexander    1  43.0   
222       2           Navratil, Mr. Michel ("Louis M Hoffman")    1  36.5   

     SibSp  Parch             Ticket      Fare Cabin  Embarked  
0        1      1         C.A. 33112   36.7500   NaN         2  
1        0      0              17465   25.9292   D17         2  
2        0      0              36865    7.7375   NaN         1  
3        2      1             243847   27.0000   NaN         2  
4        0      0           PC 17473   26.2875   E25         2  
..     ...    ...                ...       ...   ...       ...  
218      1      0  STON/O 2. 3101285    7.9250   NaN         2  
219      0      0             113050   26.5500   B38         2  
220      1      0           PC 17758  108.9000   C65         0  
221      0      0             C 7075    6.4500   NaN         2  
222      0      2             230080   26.0000    F2         2  

[223 rows x 10 columns]

In [54]:
test = test.drop(['Name', 'Ticket', 'Cabin', 'Embarked', "Sex", 'Pclass'], axis= 1)

In [55]:
test

Age  SibSp  Parch      Fare
0     8.0      1      1   36.7500
1    49.0      0      0   25.9292
2    29.0      0      0    7.7375
3    24.0      2      1   27.0000
4    36.0      0      0   26.2875
..    ...    ...    ...       ...
218  20.0      1      0    7.9250
219  45.0      0      0   26.5500
220  17.0      1      0  108.9000
221  43.0      0      0    6.4500
222  36.5      0      2   26.0000

[223 rows x 4 columns]

In [56]:
df3 = pd.DataFrame(enc, columns = col2)
df4 = pd.DataFrame(sex1, columns = col1)

In [57]:
df3['index'] = df3.index
df4['index'] = df4.index

In [58]:
test['index'] = test.index

In [59]:
test = pd.merge(test, df3, on='index')
test

Age  SibSp  Parch      Fare  index    S    C    Q   Q1
0     8.0      1      1   36.7500      0  0.0  0.0  1.0  0.0
1    49.0      0      0   25.9292      1  0.0  0.0  1.0  0.0
2    29.0      0      0    7.7375      2  0.0  1.0  0.0  0.0
3    24.0      2      1   27.0000      3  0.0  0.0  1.0  0.0
4    36.0      0      0   26.2875      4  0.0  0.0  1.0  0.0
..    ...    ...    ...       ...    ...  ...  ...  ...  ...
218  20.0      1      0    7.9250    218  0.0  0.0  1.0  0.0
219  45.0      0      0   26.5500    219  0.0  0.0  1.0  0.0
220  17.0      1      0  108.9000    220  1.0  0.0  0.0  0.0
221  43.0      0      0    6.4500    221  0.0  0.0  1.0  0.0
222  36.5      0      2   26.0000    222  0.0  0.0  1.0  0.0

[223 rows x 9 columns]

In [60]:
test = pd.merge(test, df4, on='index')
test

Age  SibSp  Parch      Fare  index    S    C    Q   Q1  Male  Female
0     8.0      1      1   36.7500      0  0.0  0.0  1.0  0.0   0.0     1.0
1    49.0      0      0   25.9292      1  0.0  0.0  1.0  0.0   1.0     0.0
2    29.0      0      0    7.7375      2  0.0  1.0  0.0  0.0   0.0     1.0
3    24.0      2      1   27.0000      3  0.0  0.0  1.0  0.0   1.0     0.0
4    36.0      0      0   26.2875      4  0.0  0.0  1.0  0.0   0.0     1.0
..    ...    ...    ...       ...    ...  ...  ...  ...  ...   ...     ...
218  20.0      1      0    7.9250    218  0.0  0.0  1.0  0.0   0.0     1.0
219  45.0      0      0   26.5500    219  0.0  0.0  1.0  0.0   0.0     1.0
220  17.0      1      0  108.9000    220  1.0  0.0  0.0  0.0   1.0     0.0
221  43.0      0      0    6.4500    221  0.0  0.0  1.0  0.0   0.0     1.0
222  36.5      0      2   26.0000    222  0.0  0.0  1.0  0.0   0.0     1.0

[223 rows x 11 columns]

In [61]:
test = pd.merge(test, df6, on='index')

In [62]:
test = test.drop(['index'], axis = 1)
test

Age  SibSp  Parch      Fare    S    C    Q   Q1  Male  Female    1    2  \
0     8.0      1      1   36.7500  0.0  0.0  1.0  0.0   0.0     1.0  0.0  1.0   
1    49.0      0      0   25.9292  0.0  0.0  1.0  0.0   1.0     0.0  1.0  0.0   
2    29.0      0      0    7.7375  0.0  1.0  0.0  0.0   0.0     1.0  0.0  0.0   
3    24.0      2      1   27.0000  0.0  0.0  1.0  0.0   1.0     0.0  0.0  1.0   
4    36.0      0      0   26.2875  0.0  0.0  1.0  0.0   0.0     1.0  1.0  0.0   
..    ...    ...    ...       ...  ...  ...  ...  ...   ...     ...  ...  ...   
218  20.0      1      0    7.9250  0.0  0.0  1.0  0.0   0.0     1.0  0.0  0.0   
219  45.0      0      0   26.5500  0.0  0.0  1.0  0.0   0.0     1.0  1.0  0.0   
220  17.0      1      0  108.9000  1.0  0.0  0.0  0.0   1.0     0.0  1.0  0.0   
221  43.0      0      0    6.4500  0.0  0.0  1.0  0.0   0.0     1.0  0.0  0.0   
222  36.5      0      2   26.0000  0.0  0.0  1.0  0.0   0.0     1.0  0.0  1.0   

       3  
0    0.0  
1    0.0  
2    1.0  
3    0.0  
4    0.0  
..   ...  
218  1.0  
219  0.0  
220  0.0  
221  1.0  
222  0.0  

[223 rows x 13 columns]

In [63]:
pred = clf.predict(test)

In [64]:
pred

array([0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0], dtype=int64)

In [65]:
np.savetxt('LRPredictions3', pred)